#!/bin/bash
#===============================================================================
#
#          FILE:  load-average
# 
#         USAGE:  ./load-average
# 
#   DESCRIPTION:  Add ldavg screen status bar
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  http://raphink.info/2008/12/follow-up-on-screen-profiles.html
#        AUTHOR:  See NOTES
#       COMPANY:  ---
#       VERSION:  1.0
#       CREATED:  12/18/2008 08:00:50 AM MST
#      REVISION:  ---
#===============================================================================

uptime | sed -e "s/.*load average: //" | tr -d " " | tr "," " "
